### Register
POST http://localhost:7242/api/auth/register
Content-Type: application/json

{
  "email": "admin@codepulse.com",
  "password": "Admin@123!",
  "confirmPassword": "Admin@123!",
  "firstName": "Admin",
  "lastName": "User"
}

###

### Login
POST http://localhost:7242/api/auth/login
Content-Type: application/json

{
  "email": "admin@codepulse.com",
  "password": "Admin@123!"
}
