using AutoMapper;
using CodePulse.Application.DTOs.CategoryPost;
using CodePulse.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Text;

namespace CodePulse.Application.Mappers
{
    public class CategoryPostMappingProfile : Profile
    {
        public CategoryPostMappingProfile()
        {
            /// CreateCategoryPostDto → BlogCategory entity
            /// ignore Id, CreatedAt, UpdatedAt since they are generated by the database or set in the domain layer
             
             CreateMap<CreateCategoryPostDto, BlogCategory>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());

            /// UpdateCategoryPostDto → BlogCategory entity
            /// Ignore timestamps — only Id comes from the DTO
             
             CreateMap<UpdateCategoryPostDto, BlogCategory>()
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());

            /// BlogCategory entity → BlogCategoryDto (response)
            CreateMap<BlogCategory, CategoryPostDto>();
        }
    }
}